// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/proto.proto

package proto;

@SuppressWarnings("ALL")
public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Info)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 offset = 1;</code>
     */
    boolean hasOffset();
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    long getOffset();

    /**
     * <code>optional uint64 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>optional uint64 length = 2;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code proto.Info}
   */
  public static final class Info extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Info)
      InfoOrBuilder {
    // Use Info.newBuilder() to construct.
    private Info(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Info(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Info defaultInstance;
    public static Info getDefaultInstance() {
      return defaultInstance;
    }

    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Info(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              offset_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Proto.internal_static_proto_Info_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Proto.internal_static_proto_Info_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Proto.Info.class, proto.Proto.Info.Builder.class);
    }

    public static com.google.protobuf.Parser<Info> PARSER =
        new com.google.protobuf.AbstractParser<Info>() {
      public Info parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Info(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Info> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private long offset_;
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 offset = 1;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private long length_;
    /**
     * <code>optional uint64 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 length = 2;</code>
     */
    public long getLength() {
      return length_;
    }

    private void initFields() {
      offset_ = 0L;
      length_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, offset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, length_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, offset_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, length_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.Proto.Info parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Info parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Info parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Info parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Info parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Info parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Proto.Info parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Proto.Info parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Proto.Info parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Info parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.Proto.Info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Info}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Info)
        proto.Proto.InfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Proto.internal_static_proto_Info_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Proto.internal_static_proto_Info_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Proto.Info.class, proto.Proto.Info.Builder.class);
      }

      // Construct using proto.Proto.Info.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        offset_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Proto.internal_static_proto_Info_descriptor;
      }

      public proto.Proto.Info getDefaultInstanceForType() {
        return proto.Proto.Info.getDefaultInstance();
      }

      public proto.Proto.Info build() {
        proto.Proto.Info result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Proto.Info buildPartial() {
        proto.Proto.Info result = new proto.Proto.Info(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Proto.Info) {
          return mergeFrom((proto.Proto.Info)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Proto.Info other) {
        if (other == proto.Proto.Info.getDefaultInstance()) return this;
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Proto.Info parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Proto.Info) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long offset_ ;
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public Builder setOffset(long value) {
        bitField0_ |= 0x00000001;
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 offset = 1;</code>
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000001);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public Builder setLength(long value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.Info)
    }

    static {
      defaultInstance = new Info(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Info)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required fixed32 magic_cookie = 1;</code>
     */
    boolean hasMagicCookie();
    /**
     * <code>required fixed32 magic_cookie = 1;</code>
     */
    int getMagicCookie();

    /**
     * <code>optional .proto.Message.MType mtype = 2;</code>
     */
    boolean hasMtype();
    /**
     * <code>optional .proto.Message.MType mtype = 2;</code>
     */
    proto.Proto.Message.MType getMtype();

    /**
     * <code>optional string obj_id = 3;</code>
     */
    boolean hasObjId();
    /**
     * <code>optional string obj_id = 3;</code>
     */
    java.lang.String getObjId();
    /**
     * <code>optional string obj_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getObjIdBytes();

    /**
     * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
     */
    boolean hasObjType();
    /**
     * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
     */
    proto.Proto.Message.ObjectType getObjType();

    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    java.util.List<proto.Proto.Info> 
        getInfoList();
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    proto.Proto.Info getInfo(int index);
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    int getInfoCount();
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    java.util.List<? extends proto.Proto.InfoOrBuilder> 
        getInfoOrBuilderList();
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    proto.Proto.InfoOrBuilder getInfoOrBuilder(
        int index);

    /**
     * <code>optional bytes data = 6;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>optional bytes error = 7;</code>
     */
    boolean hasError();
    /**
     * <code>optional bytes error = 7;</code>
     */
    com.google.protobuf.ByteString getError();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              magicCookie_ = input.readFixed32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              proto.Proto.Message.MType value = proto.Proto.Message.MType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                mtype_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              objId_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              proto.Proto.Message.ObjectType value = proto.Proto.Message.ObjectType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                objType_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                info_ = new java.util.ArrayList<proto.Proto.Info>();
                mutable_bitField0_ |= 0x00000010;
              }
              info_.add(input.readMessage(proto.Proto.Info.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              data_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000020;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          info_ = java.util.Collections.unmodifiableList(info_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Proto.internal_static_proto_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Proto.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Proto.Message.class, proto.Proto.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code proto.Message.MType}
     */
    public enum MType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AVAILABILITY_INFO_REQUEST = 5;</code>
       */
      AVAILABILITY_INFO_REQUEST(0, 5),
      /**
       * <code>AVAILABILITY_INFO_RESPONSE = 6;</code>
       */
      AVAILABILITY_INFO_RESPONSE(1, 6),
      /**
       * <code>AVAILABILITY_INFO_ABORT = 7;</code>
       */
      AVAILABILITY_INFO_ABORT(2, 7),
      /**
       * <code>AVAILABILITY_INFO_FAILURE = 8;</code>
       */
      AVAILABILITY_INFO_FAILURE(3, 8),
      /**
       * <code>DATA_REQUEST = 9;</code>
       */
      DATA_REQUEST(4, 9),
      /**
       * <code>DATA_RESPONSE = 10;</code>
       */
      DATA_RESPONSE(5, 10),
      /**
       * <code>DATA_ABORT = 11;</code>
       */
      DATA_ABORT(6, 11),
      /**
       * <code>DATA_FAILURE = 12;</code>
       */
      DATA_FAILURE(7, 12),
      ;

      /**
       * <code>AVAILABILITY_INFO_REQUEST = 5;</code>
       */
      public static final int AVAILABILITY_INFO_REQUEST_VALUE = 5;
      /**
       * <code>AVAILABILITY_INFO_RESPONSE = 6;</code>
       */
      public static final int AVAILABILITY_INFO_RESPONSE_VALUE = 6;
      /**
       * <code>AVAILABILITY_INFO_ABORT = 7;</code>
       */
      public static final int AVAILABILITY_INFO_ABORT_VALUE = 7;
      /**
       * <code>AVAILABILITY_INFO_FAILURE = 8;</code>
       */
      public static final int AVAILABILITY_INFO_FAILURE_VALUE = 8;
      /**
       * <code>DATA_REQUEST = 9;</code>
       */
      public static final int DATA_REQUEST_VALUE = 9;
      /**
       * <code>DATA_RESPONSE = 10;</code>
       */
      public static final int DATA_RESPONSE_VALUE = 10;
      /**
       * <code>DATA_ABORT = 11;</code>
       */
      public static final int DATA_ABORT_VALUE = 11;
      /**
       * <code>DATA_FAILURE = 12;</code>
       */
      public static final int DATA_FAILURE_VALUE = 12;


      public final int getNumber() { return value; }

      public static MType valueOf(int value) {
        switch (value) {
          case 5: return AVAILABILITY_INFO_REQUEST;
          case 6: return AVAILABILITY_INFO_RESPONSE;
          case 7: return AVAILABILITY_INFO_ABORT;
          case 8: return AVAILABILITY_INFO_FAILURE;
          case 9: return DATA_REQUEST;
          case 10: return DATA_RESPONSE;
          case 11: return DATA_ABORT;
          case 12: return DATA_FAILURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MType>() {
              public MType findValueByNumber(int number) {
                return MType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.Proto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MType[] VALUES = values();

      public static MType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      MType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Message.MType)
    }

    /**
     * Protobuf enum {@code proto.Message.ObjectType}
     */
    public enum ObjectType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FILE = 1;</code>
       */
      FILE(0, 1),
      /**
       * <code>PATCH = 2;</code>
       */
      PATCH(1, 2),
      ;

      /**
       * <code>FILE = 1;</code>
       */
      public static final int FILE_VALUE = 1;
      /**
       * <code>PATCH = 2;</code>
       */
      public static final int PATCH_VALUE = 2;


      public final int getNumber() { return value; }

      public static ObjectType valueOf(int value) {
        switch (value) {
          case 1: return FILE;
          case 2: return PATCH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ObjectType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ObjectType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ObjectType>() {
              public ObjectType findValueByNumber(int number) {
                return ObjectType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.Proto.Message.getDescriptor().getEnumTypes().get(1);
      }

      private static final ObjectType[] VALUES = values();

      public static ObjectType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      ObjectType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Message.ObjectType)
    }

    private int bitField0_;
    public static final int MAGIC_COOKIE_FIELD_NUMBER = 1;
    private int magicCookie_;
    /**
     * <code>required fixed32 magic_cookie = 1;</code>
     */
    public boolean hasMagicCookie() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required fixed32 magic_cookie = 1;</code>
     */
    public int getMagicCookie() {
      return magicCookie_;
    }

    public static final int MTYPE_FIELD_NUMBER = 2;
    private proto.Proto.Message.MType mtype_;
    /**
     * <code>optional .proto.Message.MType mtype = 2;</code>
     */
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.Message.MType mtype = 2;</code>
     */
    public proto.Proto.Message.MType getMtype() {
      return mtype_;
    }

    public static final int OBJ_ID_FIELD_NUMBER = 3;
    private java.lang.Object objId_;
    /**
     * <code>optional string obj_id = 3;</code>
     */
    public boolean hasObjId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string obj_id = 3;</code>
     */
    public java.lang.String getObjId() {
      java.lang.Object ref = objId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string obj_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getObjIdBytes() {
      java.lang.Object ref = objId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJ_TYPE_FIELD_NUMBER = 4;
    private proto.Proto.Message.ObjectType objType_;
    /**
     * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
     */
    public boolean hasObjType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
     */
    public proto.Proto.Message.ObjectType getObjType() {
      return objType_;
    }

    public static final int INFO_FIELD_NUMBER = 5;
    private java.util.List<proto.Proto.Info> info_;
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    public java.util.List<proto.Proto.Info> getInfoList() {
      return info_;
    }
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    public java.util.List<? extends proto.Proto.InfoOrBuilder> 
        getInfoOrBuilderList() {
      return info_;
    }
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    public proto.Proto.Info getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated .proto.Info info = 5;</code>
     */
    public proto.Proto.InfoOrBuilder getInfoOrBuilder(
        int index) {
      return info_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 6;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int ERROR_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString error_;
    /**
     * <code>optional bytes error = 7;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes error = 7;</code>
     */
    public com.google.protobuf.ByteString getError() {
      return error_;
    }

    private void initFields() {
      magicCookie_ = 0;
      mtype_ = proto.Proto.Message.MType.AVAILABILITY_INFO_REQUEST;
      objId_ = "";
      objType_ = proto.Proto.Message.ObjectType.FILE;
      info_ = java.util.Collections.emptyList();
      data_ = com.google.protobuf.ByteString.EMPTY;
      error_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMagicCookie()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, magicCookie_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, mtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getObjIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, objType_.getNumber());
      }
      for (int i = 0; i < info_.size(); i++) {
        output.writeMessage(5, info_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, data_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, error_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, magicCookie_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mtype_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getObjIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, objType_.getNumber());
      }
      for (int i = 0; i < info_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, info_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, error_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.Proto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Proto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Proto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.Proto.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        proto.Proto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Proto.internal_static_proto_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Proto.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Proto.Message.class, proto.Proto.Message.Builder.class);
      }

      // Construct using proto.Proto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        magicCookie_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        mtype_ = proto.Proto.Message.MType.AVAILABILITY_INFO_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000002);
        objId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        objType_ = proto.Proto.Message.ObjectType.FILE;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          infoBuilder_.clear();
        }
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        error_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Proto.internal_static_proto_Message_descriptor;
      }

      public proto.Proto.Message getDefaultInstanceForType() {
        return proto.Proto.Message.getDefaultInstance();
      }

      public proto.Proto.Message build() {
        proto.Proto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Proto.Message buildPartial() {
        proto.Proto.Message result = new proto.Proto.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.magicCookie_ = magicCookie_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mtype_ = mtype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.objId_ = objId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.objType_ = objType_;
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            info_ = java.util.Collections.unmodifiableList(info_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Proto.Message) {
          return mergeFrom((proto.Proto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Proto.Message other) {
        if (other == proto.Proto.Message.getDefaultInstance()) return this;
        if (other.hasMagicCookie()) {
          setMagicCookie(other.getMagicCookie());
        }
        if (other.hasMtype()) {
          setMtype(other.getMtype());
        }
        if (other.hasObjId()) {
          bitField0_ |= 0x00000004;
          objId_ = other.objId_;
          onChanged();
        }
        if (other.hasObjType()) {
          setObjType(other.getObjType());
        }
        if (infoBuilder_ == null) {
          if (!other.info_.isEmpty()) {
            if (info_.isEmpty()) {
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureInfoIsMutable();
              info_.addAll(other.info_);
            }
            onChanged();
          }
        } else {
          if (!other.info_.isEmpty()) {
            if (infoBuilder_.isEmpty()) {
              infoBuilder_.dispose();
              infoBuilder_ = null;
              info_ = other.info_;
              bitField0_ = (bitField0_ & ~0x00000010);
              infoBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInfoFieldBuilder() : null;
            } else {
              infoBuilder_.addAllMessages(other.info_);
            }
          }
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return hasMagicCookie();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Proto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Proto.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int magicCookie_ ;
      /**
       * <code>required fixed32 magic_cookie = 1;</code>
       */
      public boolean hasMagicCookie() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required fixed32 magic_cookie = 1;</code>
       */
      public int getMagicCookie() {
        return magicCookie_;
      }
      /**
       * <code>required fixed32 magic_cookie = 1;</code>
       */
      public Builder setMagicCookie(int value) {
        bitField0_ |= 0x00000001;
        magicCookie_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 magic_cookie = 1;</code>
       */
      public Builder clearMagicCookie() {
        bitField0_ = (bitField0_ & ~0x00000001);
        magicCookie_ = 0;
        onChanged();
        return this;
      }

      private proto.Proto.Message.MType mtype_ = proto.Proto.Message.MType.AVAILABILITY_INFO_REQUEST;
      /**
       * <code>optional .proto.Message.MType mtype = 2;</code>
       */
      public boolean hasMtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.Message.MType mtype = 2;</code>
       */
      public proto.Proto.Message.MType getMtype() {
        return mtype_;
      }
      /**
       * <code>optional .proto.Message.MType mtype = 2;</code>
       */
      public Builder setMtype(proto.Proto.Message.MType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        mtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.Message.MType mtype = 2;</code>
       */
      public Builder clearMtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mtype_ = proto.Proto.Message.MType.AVAILABILITY_INFO_REQUEST;
        onChanged();
        return this;
      }

      private java.lang.Object objId_ = "";
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public boolean hasObjId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public java.lang.String getObjId() {
        java.lang.Object ref = objId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            objId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getObjIdBytes() {
        java.lang.Object ref = objId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public Builder setObjId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public Builder clearObjId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        objId_ = getDefaultInstance().getObjId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string obj_id = 3;</code>
       */
      public Builder setObjIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        objId_ = value;
        onChanged();
        return this;
      }

      private proto.Proto.Message.ObjectType objType_ = proto.Proto.Message.ObjectType.FILE;
      /**
       * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
       */
      public boolean hasObjType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
       */
      public proto.Proto.Message.ObjectType getObjType() {
        return objType_;
      }
      /**
       * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
       */
      public Builder setObjType(proto.Proto.Message.ObjectType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        objType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.Message.ObjectType obj_type = 4;</code>
       */
      public Builder clearObjType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        objType_ = proto.Proto.Message.ObjectType.FILE;
        onChanged();
        return this;
      }

      private java.util.List<proto.Proto.Info> info_ =
        java.util.Collections.emptyList();
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          info_ = new java.util.ArrayList<proto.Proto.Info>(info_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Proto.Info, proto.Proto.Info.Builder, proto.Proto.InfoOrBuilder> infoBuilder_;

      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public java.util.List<proto.Proto.Info> getInfoList() {
        if (infoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(info_);
        } else {
          return infoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public int getInfoCount() {
        if (infoBuilder_ == null) {
          return info_.size();
        } else {
          return infoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public proto.Proto.Info getInfo(int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);
        } else {
          return infoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder setInfo(
          int index, proto.Proto.Info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.set(index, value);
          onChanged();
        } else {
          infoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder setInfo(
          int index, proto.Proto.Info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.set(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder addInfo(proto.Proto.Info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(value);
          onChanged();
        } else {
          infoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder addInfo(
          int index, proto.Proto.Info value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInfoIsMutable();
          info_.add(index, value);
          onChanged();
        } else {
          infoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder addInfo(
          proto.Proto.Info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder addInfo(
          int index, proto.Proto.Info.Builder builderForValue) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.add(index, builderForValue.build());
          onChanged();
        } else {
          infoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder addAllInfo(
          java.lang.Iterable<? extends proto.Proto.Info> values) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, info_);
          onChanged();
        } else {
          infoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public Builder removeInfo(int index) {
        if (infoBuilder_ == null) {
          ensureInfoIsMutable();
          info_.remove(index);
          onChanged();
        } else {
          infoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public proto.Proto.Info.Builder getInfoBuilder(
          int index) {
        return getInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public proto.Proto.InfoOrBuilder getInfoOrBuilder(
          int index) {
        if (infoBuilder_ == null) {
          return info_.get(index);  } else {
          return infoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public java.util.List<? extends proto.Proto.InfoOrBuilder> 
           getInfoOrBuilderList() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(info_);
        }
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public proto.Proto.Info.Builder addInfoBuilder() {
        return getInfoFieldBuilder().addBuilder(
            proto.Proto.Info.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public proto.Proto.Info.Builder addInfoBuilder(
          int index) {
        return getInfoFieldBuilder().addBuilder(
            index, proto.Proto.Info.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Info info = 5;</code>
       */
      public java.util.List<proto.Proto.Info.Builder> 
           getInfoBuilderList() {
        return getInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Proto.Info, proto.Proto.Info.Builder, proto.Proto.InfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Proto.Info, proto.Proto.Info.Builder, proto.Proto.InfoOrBuilder>(
                  info_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 6;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString error_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes error = 7;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes error = 7;</code>
       */
      public com.google.protobuf.ByteString getError() {
        return error_;
      }
      /**
       * <code>optional bytes error = 7;</code>
       */
      public Builder setError(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes error = 7;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000040);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
  }

  public interface MessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Messages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    java.util.List<proto.Proto.Message> 
        getMsgList();
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    proto.Proto.Message getMsg(int index);
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    int getMsgCount();
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    java.util.List<? extends proto.Proto.MessageOrBuilder> 
        getMsgOrBuilderList();
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    proto.Proto.MessageOrBuilder getMsgOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Messages}
   */
  public static final class Messages extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.Messages)
      MessagesOrBuilder {
    // Use Messages.newBuilder() to construct.
    private Messages(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Messages(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Messages defaultInstance;
    public static Messages getDefaultInstance() {
      return defaultInstance;
    }

    public Messages getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Messages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                msg_ = new java.util.ArrayList<proto.Proto.Message>();
                mutable_bitField0_ |= 0x00000001;
              }
              msg_.add(input.readMessage(proto.Proto.Message.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = java.util.Collections.unmodifiableList(msg_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Proto.internal_static_proto_Messages_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Proto.internal_static_proto_Messages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Proto.Messages.class, proto.Proto.Messages.Builder.class);
    }

    public static com.google.protobuf.Parser<Messages> PARSER =
        new com.google.protobuf.AbstractParser<Messages>() {
      public Messages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Messages(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Messages> getParserForType() {
      return PARSER;
    }

    public static final int MSG_FIELD_NUMBER = 11;
    private java.util.List<proto.Proto.Message> msg_;
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    public java.util.List<proto.Proto.Message> getMsgList() {
      return msg_;
    }
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    public java.util.List<? extends proto.Proto.MessageOrBuilder> 
        getMsgOrBuilderList() {
      return msg_;
    }
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    public int getMsgCount() {
      return msg_.size();
    }
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    public proto.Proto.Message getMsg(int index) {
      return msg_.get(index);
    }
    /**
     * <code>repeated .proto.Message msg = 11;</code>
     */
    public proto.Proto.MessageOrBuilder getMsgOrBuilder(
        int index) {
      return msg_.get(index);
    }

    private void initFields() {
      msg_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getMsgCount(); i++) {
        if (!getMsg(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msg_.size(); i++) {
        output.writeMessage(11, msg_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < msg_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, msg_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.Proto.Messages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Messages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Messages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Proto.Messages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Proto.Messages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Messages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.Proto.Messages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.Proto.Messages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.Proto.Messages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.Proto.Messages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.Proto.Messages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Messages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Messages)
        proto.Proto.MessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Proto.internal_static_proto_Messages_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Proto.internal_static_proto_Messages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Proto.Messages.class, proto.Proto.Messages.Builder.class);
      }

      // Construct using proto.Proto.Messages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          msgBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Proto.internal_static_proto_Messages_descriptor;
      }

      public proto.Proto.Messages getDefaultInstanceForType() {
        return proto.Proto.Messages.getDefaultInstance();
      }

      public proto.Proto.Messages build() {
        proto.Proto.Messages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.Proto.Messages buildPartial() {
        proto.Proto.Messages result = new proto.Proto.Messages(this);
        int from_bitField0_ = bitField0_;
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            msg_ = java.util.Collections.unmodifiableList(msg_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Proto.Messages) {
          return mergeFrom((proto.Proto.Messages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Proto.Messages other) {
        if (other == proto.Proto.Messages.getDefaultInstance()) return this;
        if (msgBuilder_ == null) {
          if (!other.msg_.isEmpty()) {
            if (msg_.isEmpty()) {
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMsgIsMutable();
              msg_.addAll(other.msg_);
            }
            onChanged();
          }
        } else {
          if (!other.msg_.isEmpty()) {
            if (msgBuilder_.isEmpty()) {
              msgBuilder_.dispose();
              msgBuilder_ = null;
              msg_ = other.msg_;
              bitField0_ = (bitField0_ & ~0x00000001);
              msgBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgFieldBuilder() : null;
            } else {
              msgBuilder_.addAllMessages(other.msg_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getMsgCount(); i++) {
          if (!getMsg(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Proto.Messages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Proto.Messages) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Proto.Message> msg_ =
        java.util.Collections.emptyList();
      private void ensureMsgIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msg_ = new java.util.ArrayList<proto.Proto.Message>(msg_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Proto.Message, proto.Proto.Message.Builder, proto.Proto.MessageOrBuilder> msgBuilder_;

      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public java.util.List<proto.Proto.Message> getMsgList() {
        if (msgBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msg_);
        } else {
          return msgBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public int getMsgCount() {
        if (msgBuilder_ == null) {
          return msg_.size();
        } else {
          return msgBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public proto.Proto.Message getMsg(int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);
        } else {
          return msgBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder setMsg(
          int index, proto.Proto.Message value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.set(index, value);
          onChanged();
        } else {
          msgBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder setMsg(
          int index, proto.Proto.Message.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder addMsg(proto.Proto.Message value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(value);
          onChanged();
        } else {
          msgBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder addMsg(
          int index, proto.Proto.Message value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgIsMutable();
          msg_.add(index, value);
          onChanged();
        } else {
          msgBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder addMsg(
          proto.Proto.Message.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder addMsg(
          int index, proto.Proto.Message.Builder builderForValue) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder addAllMsg(
          java.lang.Iterable<? extends proto.Proto.Message> values) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, msg_);
          onChanged();
        } else {
          msgBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public Builder removeMsg(int index) {
        if (msgBuilder_ == null) {
          ensureMsgIsMutable();
          msg_.remove(index);
          onChanged();
        } else {
          msgBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public proto.Proto.Message.Builder getMsgBuilder(
          int index) {
        return getMsgFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public proto.Proto.MessageOrBuilder getMsgOrBuilder(
          int index) {
        if (msgBuilder_ == null) {
          return msg_.get(index);  } else {
          return msgBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public java.util.List<? extends proto.Proto.MessageOrBuilder> 
           getMsgOrBuilderList() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msg_);
        }
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public proto.Proto.Message.Builder addMsgBuilder() {
        return getMsgFieldBuilder().addBuilder(
            proto.Proto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public proto.Proto.Message.Builder addMsgBuilder(
          int index) {
        return getMsgFieldBuilder().addBuilder(
            index, proto.Proto.Message.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Message msg = 11;</code>
       */
      public java.util.List<proto.Proto.Message.Builder> 
           getMsgBuilderList() {
        return getMsgFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.Proto.Message, proto.Proto.Message.Builder, proto.Proto.MessageOrBuilder> 
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.Proto.Message, proto.Proto.Message.Builder, proto.Proto.MessageOrBuilder>(
                  msg_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.Messages)
    }

    static {
      defaultInstance = new Messages(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.Messages)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Info_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Info_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Messages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Messages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/proto.proto\022\005proto\"&\n\004Info\022\016\n\006of" +
      "fset\030\001 \001(\004\022\016\n\006length\030\002 \001(\004\"\250\003\n\007Message\022\024" +
      "\n\014magic_cookie\030\001 \002(\007\022#\n\005mtype\030\002 \001(\0162\024.pr" +
      "oto.Message.MType\022\016\n\006obj_id\030\003 \001(\t\022+\n\010obj" +
      "_type\030\004 \001(\0162\031.proto.Message.ObjectType\022\031" +
      "\n\004info\030\005 \003(\0132\013.proto.Info\022\014\n\004data\030\006 \001(\014\022" +
      "\r\n\005error\030\007 \001(\014\"\311\001\n\005MType\022\035\n\031AVAILABILITY" +
      "_INFO_REQUEST\020\005\022\036\n\032AVAILABILITY_INFO_RES" +
      "PONSE\020\006\022\033\n\027AVAILABILITY_INFO_ABORT\020\007\022\035\n\031" +
      "AVAILABILITY_INFO_FAILURE\020\010\022\020\n\014DATA_REQU",
      "EST\020\t\022\021\n\rDATA_RESPONSE\020\n\022\016\n\nDATA_ABORT\020\013" +
      "\022\020\n\014DATA_FAILURE\020\014\"!\n\nObjectType\022\010\n\004FILE" +
      "\020\001\022\t\n\005PATCH\020\002\"\'\n\010Messages\022\033\n\003msg\030\013 \003(\0132\016" +
      ".proto.Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Info_descriptor,
        new java.lang.String[] { "Offset", "Length", });
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "MagicCookie", "Mtype", "ObjId", "ObjType", "Info", "Data", "Error", });
    internal_static_proto_Messages_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Messages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_Messages_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
